version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql", "-c", "log_filename=postgresql-%a.log"]
    networks:
      - spring-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  spring-api-image:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - ./logs/spring-api:/var/log/spring
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE}
      - DB_HOST=postgres
      - LOGGING_FILE_PATH=/var/log/spring
      - DB_PORT=${DB_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - spring-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

networks:
  spring-network:


volumes:
  postgres-data:
