version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  spring-api-image:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - spring-api-logs:/var/log/spring
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE}
      - DB_HOST=postgres
      - LOGGING_FILE_PATH=/var/log/spring
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    networks:
      - spring-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

networks:
  spring-network:

volumes:
  postgres-data:
  spring-api-logs:
