-- =========================================================
-- CUSOL - DDL PostgreSQL
-- Esquema generado a partir del dump proporcionado
-- Compatible con PostgreSQL 16+
-- =========================================================

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

CREATE SCHEMA IF NOT EXISTS public;

-- =========================================================
-- TABLAS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.academic_period (
    period_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    end_date date,
    start_date date,
    name varchar(100)
);

CREATE TABLE IF NOT EXISTS public.users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no_expired boolean,
    account_no_locked boolean,
    credential_no_expired boolean,
    is_enabled boolean,
    last_session timestamp(6) without time zone,
    first_name varchar(128),
    last_name varchar(128),
    username varchar(128),
    email varchar(250) NOT NULL,
    password varchar(256) NOT NULL,
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.roles (
    role_guid uuid PRIMARY KEY,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    name varchar(50) NOT NULL,
    CONSTRAINT roles_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.faculty (
    faculty_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);

CREATE TABLE IF NOT EXISTS public.day_of_week (
    day_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(16)
);

CREATE TABLE IF NOT EXISTS public.classroom (
    classroom_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_capacity integer,
    number integer NOT NULL,
    type varchar(100),
    building varchar(256),
    campus varchar(256)
);

CREATE TABLE IF NOT EXISTS public.audit_log (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp(6) without time zone,
    user_id bigint,
    action varchar(256),
    module varchar(256),
    origin_ip varchar(256),
    CONSTRAINT audit_log_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.school (
    school_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id bigint,
    name varchar(100)
);

CREATE TABLE IF NOT EXISTS public.subject (
    subject_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credits integer NOT NULL,
    practice_hours integer NOT NULL,
    theory_hours integer NOT NULL,
    school_id bigint,
    code varchar(250),
    name varchar(250)
);

CREATE TABLE IF NOT EXISTS public.teacher (
    teacher_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    availability varchar(250),
    department varchar(250)
);

CREATE TABLE IF NOT EXISTS public.groups (
    group_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capacity integer NOT NULL,
    period_id bigint,
    subject_id bigint,
    teacher_id bigint,
    group_name varchar(250)
);

CREATE TABLE IF NOT EXISTS public.class (
    class_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint,
    user_id bigint,
    class_type varchar(128)
);

CREATE TABLE IF NOT EXISTS public.class_hour (
    class_hour_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hour time(6) without time zone,
    classroom_id bigint,
    day_id bigint,
    group_id bigint
);

CREATE TABLE IF NOT EXISTS public.schedule (
    schedule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id bigint,
    user_id bigint,
    CONSTRAINT schedule_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_roles (
    user_id bigint NOT NULL,
    role_guid uuid NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_guid)
);

-- =========================================================
-- FOREIGN KEYS
-- =========================================================

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT fkk4alalwu62gj4tfbgfefll3tu
    FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.school
    ADD CONSTRAINT fkflxxoc9bllhsatkm9f3qqv19f
    FOREIGN KEY (faculty_id) REFERENCES public.faculty(faculty_id);

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT fkg9ahxfklvfv5o2d8ejweibfo8
    FOREIGN KEY (school_id) REFERENCES public.school(school_id);

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT fkcp1vpkh4bh0qux9vtvs0fkwrn
    FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fk5ltiwe1lwq5u03wcopmh34rd8
    FOREIGN KEY (period_id) REFERENCES public.academic_period(period_id);

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fkh41v53xm83rq9vspgdjqjjsm2
    FOREIGN KEY (teacher_id) REFERENCES public.teacher(teacher_id);

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT fkpduc2peqan6ivl2y1gcpad4qd
    FOREIGN KEY (subject_id) REFERENCES public.subject(subject_id);

ALTER TABLE ONLY public.class
    ADD CONSTRAINT fklbaki8a9xaoypxd2pte3vtwmi
    FOREIGN KEY (group_id) REFERENCES public.groups(group_id);

ALTER TABLE ONLY public.class
    ADD CONSTRAINT fkeg1d23px9j4dc1eadu1hmpcf3
    FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.class_hour
    ADD CONSTRAINT fkgfg6w7c0cm71ogs0n7i5858ef
    FOREIGN KEY (classroom_id) REFERENCES public.classroom(classroom_id);

ALTER TABLE ONLY public.class_hour
    ADD CONSTRAINT fkgsi4ulpggesf54tygqx81icn1
    FOREIGN KEY (day_id) REFERENCES public.day_of_week(day_id);

ALTER TABLE ONLY public.class_hour
    ADD CONSTRAINT fka4tho89bqrxnle81ua0oqkb67
    FOREIGN KEY (group_id) REFERENCES public.groups(group_id);

ALTER TABLE ONLY public.schedule
    ADD CONSTRAINT fkqqv2rqy5xxw2oyhie35seyclw
    FOREIGN KEY (class_id) REFERENCES public.class(class_id);

ALTER TABLE ONLY public.schedule
    ADD CONSTRAINT fkdn5svbxyacce1gpfiawk7iqtc
    FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f
    FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkb23g9xsd1xwow8wmdse2c7ycs
    FOREIGN KEY (role_guid) REFERENCES public.roles(role_guid);

-- End of migration
