spring.application.name=uis-schedule-system-backend

#Database Config
spring.datasource.url=jdbc:postgresql://postgres:5432/scheduleDB
spring.datasource.username=cusolOficial
spring.datasource.password=A4352k#_M
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Security Config
spring.security.user.name=svensson
spring.security.user.password=1234

#JWT Config
jwt.secret=a2b8d4e6f8a0c2e4b6d8f0a2c4e6f8a0c2e4b6d8f0a2c4e6f8a0c2e4b6d8f0a2