name: Deploy Backend

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: [self-hosted, backend-pi]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compilar con Maven
        run: mvn compile -Dmaven.compiler.release=17 -q

      - name: Rebuild y reinicio del contenedor
        working-directory: /home/dev/proyects
        run: |
          docker-compose stop backend-spring-api
          docker-compose rm -f backend-spring-api
          docker-compose build --no-cache backend-spring-api
          docker-compose up -d backend-spring-apideploy
